# Docs: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
    schedule:
      interval: 'quarterly'
    cooldown:
      default-days: 2
    groups:
      minor-and-patch:
        patterns: ['*']
        update-types: ['minor', 'patch']
