name: Run frontend CI on push

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - '.firebaserc'
      - '.prettierignore'
      - '.prettierrc'
      - 'astro.config.mjs'
      - 'eslint.config.mjs'
      - 'firebase.json'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.github/workflows/frontend-ci.yml'

permissions:
  contents: read

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-ci:
    uses: ./.github/workflows/reusable-node-ci.yml
    with:
      node-version: '24'
      run-lint: true
      run-build: true
