name: Run frontend CI on push

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - '.firebaserc'
      - '.prettierignore'
      - '.prettierrc'
      - 'astro.config.mjs'
      - 'eslint.config.mjs'
      - 'firebase.json'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.github/workflows/frontend-ci.yml'

permissions:
  contents: read

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
